### ISSUE TITLE
[builder] add retries / harden H5AD staging code in case of transient errors

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene-census#311]
The H5AD staging (download) code has a number of rare errors that we should protect against, on the expectation that they are transient:
* an occasional 400 / 403 error on the presigned URL GET
* (seen twice) truncated file, no error (code has been added to generate an error if this occurs)

For future automation, it would be good to retry these, and only stop the build if the error occurs more than a few times.  In other words:
* capture and classify errors which are likely transient
* retry N times, with a back-off in case the issue is capacity related

**Comment by atolopko-czi** [comment]
Another occurrence:
```
  File "/usr/local/lib/python3.10/dist-packages/cellxgene_census_builder/build_soma/source_assets.py", line 59, in copy_file
    return _copy_file(*args)
  File "/usr/local/lib/python3.10/dist-packages/cellxgene_census_builder/build_soma/source_assets.py", line 48, in _copy_file
    fs.get_file(dataset.corpora_asset_h5ad_uri, dataset_path)
  File "/usr/local/lib/python3.10/dist-packages/fsspec/asyn.py", line 115, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fsspec/asyn.py", line 98, in sync
    raise FSTimeoutError from return_result
fsspec.exceptions.FSTimeoutError
```

**Comment by bkmartinjr** [comment]
Have recently seen another error which would benefit from this retry logic.

```
2023-05-22 20:06:12 411     INFO     Staging c2876b1b-06d8-4d96-a56b-5304f815b99a (1 of 805) complete
2023-05-22 20:06:14 7       CRITICAL Caught exception, exiting
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.10/dist-packages/cellxgene_census_builder/build_soma/source_assets.py", line 59, in copy_file
    return _copy_file(*args)
  File "/usr/local/lib/python3.10/dist-packages/cellxgene_census_builder/build_soma/source_assets.py", line 48, in _copy_file
    fs.get_file(dataset.dataset_asset_h5ad_uri, dataset_path)
  File "/usr/local/lib/python3.10/dist-packages/fsspec/asyn.py", line 115, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fsspec/asyn.py", line 100, in sync
    raise return_result
  File "/usr/local/lib/python3.10/dist-packages/fsspec/asyn.py", line 55, in _runner
    result[0] = await coro
  File "/usr/local/lib/python3.10/dist-packages/fsspec/implementations/http.py", line 257, in _get_file
    chunk = await r.content.read(chunk_size)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 385, in read
    await self._wait("read")
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
"""
```

I _suspect_ it was caused by link-level instability (this from output of `dmesg`):
```
[ 3604.246349] docker0: port 1(veth12f4f71) entered blocking state
[ 3604.246354] docker0: port 1(veth12f4f71) entered disabled state
[ 3604.246416] device veth12f4f71 entered promiscuous mode
[ 3604.439765] eth0: renamed from vethf92913f
[ 3604.468614] IPv6: ADDRCONF(NETDEV_CHANGE): veth12f4f71: link becomes ready
[ 3604.468706] docker0: port 1(veth12f4f71) entered blocking state
[ 3604.468710] docker0: port 1(veth12f4f71) entered forwarding state
```

**Comment by brianraymor** [comment]
Per triage, this will be included in the census builder "automation" epic.

**Comment by bkmartinjr** [comment]
I am still seeing these errors.  In this case:
* there was no link instability log messages (eg., dmesg was clean)
* the error was a `aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed` -- [conditions in which this will be raised](https://docs.aiohttp.org/en/stable/client_reference.html#client-exceptions) suggest an upstream issue.

I'm going to grab this bug and add a limited number of retries in the Builder, as a defensive measure.
