### ISSUE TITLE
Installation Issues for Geneformer

### ISSUE THREAD

**Issue by drneavin** [chanzuckerberg/cellxgene-census#950]
## Describe the bug

I'm running into issues with loading some of the libraries required for running Geneformer using the Census model. I installed the required packages listed on the tutorial [Requirements](https://chanzuckerberg.github.io/cellxgene-census/notebooks/analysis_demo/comp_bio_geneformer_prediction.html#Requirements). However, when I then tried to load the required packages in python, I ran into some issues that I couldn't resolve. Specifically, this applies to the following:

```
from cellxgene_census.experimental.ml.huggingface import GeneformerTokenizer
```

The first time I try to import it, I receive the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/directflow/SCCGGroupShare/projects/lacgra/.conda/envs/cellxgene/lib/python3.11/site-packages/cellxgene_census/experimental/ml/__init__.py", line 5, in <module>
    from .pytorch import ExperimentDataPipe, Stats, experiment_dataloader
  File "/directflow/SCCGGroupShare/projects/lacgra/.conda/envs/cellxgene/lib/python3.11/site-packages/cellxgene_census/experimental/ml/pytorch.py", line 13, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
```

So I then I installed `psutil` and it throws a similar error about `torchdata`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/directflow/SCCGGroupShare/projects/DrewNeavin/software/anaconda3/envs/census_geneformer/lib/python3.11/site-packages/cellxgene_census/experimental/ml/__init__.py", line 5, in <module>
    from .pytorch import ExperimentDataPipe, Stats, experiment_dataloader
  File "/directflow/SCCGGroupShare/projects/DrewNeavin/software/anaconda3/envs/census_geneformer/lib/python3.11/site-packages/cellxgene_census/experimental/ml/pytorch.py", line 18, in <module>
    import torchdata.datapipes.iter as pipes
ModuleNotFoundError: No module named 'torchdata'
```

so I installed `torchdata` and it throws an error about `scipy` and `matrix`:

```
Traceback (most recent call last):
  File "/directflow/SCCGGroupShare/projects/DrewNeavin/software/anaconda3/envs/census_geneformer/lib/python3.11/site-packages/scipy/__init__.py", line 137, in __getattr__
    return globals()[name]
           ~~~~~~~~~^^^^^^
KeyError: 'matrix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/directflow/SCCGGroupShare/projects/DrewNeavin/software/anaconda3/envs/census_geneformer/lib/python3.11/site-packages/cellxgene_census/experimental/ml/__init__.py", line 5, in <module>
    from .pytorch import ExperimentDataPipe, Stats, experiment_dataloader
  File "/directflow/SCCGGroupShare/projects/DrewNeavin/software/anaconda3/envs/census_geneformer/lib/python3.11/site-packages/cellxgene_census/experimental/ml/pytorch.py", line 41, in <module>
    class _SOMAChunk:
  File "/directflow/SCCGGroupShare/projects/DrewNeavin/software/anaconda3/envs/census_geneformer/lib/python3.11/site-packages/cellxgene_census/experimental/ml/pytorch.py", line 51, in _SOMAChunk
    X: scipy.matrix
       ^^^^^^^^^^^^
  File "/directflow/SCCGGroupShare/projects/DrewNeavin/software/anaconda3/envs/census_geneformer/lib/python3.11/site-packages/scipy/__init__.py", line 139, in __getattr__
    raise AttributeError(
AttributeError: Module 'scipy' has no attribute 'matrix'
```

However, I can import `scipy` and I don't see any evidence that it has an attribute `matrix`:

```
>>>print(hasattr(scipy,'matrix'))
False
```

I think it's also important to note that one of the packages (I think Geneformer) requires python version between 3.7 and 3.11. I have tried this with three different python versions: 3.10.13, 3.11.0 and 3.11.7 all with the same result.

## To Reproduce

1. Start a new conda environment with python between 3.7 and 3.10
2. Install census cellxgene with `pip install -U cellxgene-census`
3. Install git lfs with conda: `conda install conda-forge::git-lfs`
4. Install geneformer following installation instructions:
    ```
    git lfs install
    git clone https://huggingface.co/ctheodoris/Geneformer
    cd Geneformer
    pip install .
    ```
5. Install AWS command line interface with conda: `conda install conda-forge::awscli`
6. Start python and import packages:

    ```
    import cellxgene_census
    import json
    import warnings
    
    warnings.filterwarnings("ignore")
    
    from transformers import BertForSequenceClassification
    from transformers import Trainer
    from geneformer import DataCollatorForCellClassification
    from geneformer import TranscriptomeTokenizer
    from geneformer import EmbExtractor
    from cellxgene_census.experimental import get_embedding
    from cellxgene_census.experimental.ml.huggingface import GeneformerTokenizer
    ````

## Expected behavior

I expect the package to load without issue but run into errors described above and unable to identify how to rectify it.

## Environment

Provide a description of your system and the software versions.

HPC:
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- Software versions:
```
# packages in environment at /directflow/SCCGGroupShare/projects/DrewNeavin/software/anaconda3/envs/geneformer:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
accelerate                0.26.1                   pypi_0    pypi
accumulation-tree         0.6.2                    pypi_0    pypi
aiobotocore               2.11.0                   pypi_0    pypi
aiohttp                   3.9.1                    pypi_0    pypi
aioitertools              0.11.0                   pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
anndata                   0.10.4                   pypi_0    pypi
array-api-compat          1.4.1                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
aws-c-auth                0.7.8                h538f98c_2    conda-forge
aws-c-cal                 0.6.9                h5d48c4d_2    conda-forge
aws-c-common              0.9.10               hd590300_0    conda-forge
aws-c-compression         0.2.17               h7f92143_7    conda-forge
aws-c-event-stream        0.3.2                h0bcb0bb_8    conda-forge
aws-c-http                0.7.14               hd268abd_3    conda-forge
aws-c-io                  0.13.36              he0cd244_2    conda-forge
aws-c-mqtt                0.9.10               h35285c7_2    conda-forge
aws-c-s3                  0.4.4                h0448019_0    conda-forge
aws-c-sdkutils            0.1.13               h7f92143_0    conda-forge
aws-checksums             0.1.17               h7f92143_6    conda-forge
awscli                    2.15.13         py310hff52083_0    conda-forge
awscrt                    0.19.19         py310h43b4219_2    conda-forge
botocore                  1.34.22                  pypi_0    pypi
brotli-python             1.1.0           py310hc6cd4ac_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
cellxgene-census          1.9.1                    pypi_0    pypi
certifi                   2023.11.17               pypi_0    pypi
cffi                      1.16.0          py310h2fee648_0    conda-forge
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0                    pypi_0    pypi
cryptography              40.0.2          py310h34c0648_0    conda-forge
cycler                    0.12.1                   pypi_0    pypi
datasets                  2.16.1                   pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
distro                    1.8.0              pyhd8ed1ab_0    conda-forge
docutils                  0.19            py310hff52083_1    conda-forge
exceptiongroup            1.2.0                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
fonttools                 4.47.2                   pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2023.12.2                pypi_0    pypi
geneformer                0.1.0                    pypi_0    pypi
git-lfs                   3.4.1                ha770c72_0    conda-forge
h5py                      3.10.0                   pypi_0    pypi
huggingface-hub           0.20.3                   pypi_0    pypi
idna                      3.6                      pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.3.2                    pypi_0    pypi
jsonschema                4.21.1                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvmlite                  0.39.1                   pypi_0    pypi
loompy                    3.0.7                    pypi_0    pypi
markupsafe                2.1.4                    pypi_0    pypi
matplotlib                3.8.2                    pypi_0    pypi
matrix                    3.0.0                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.0.7                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.15                  pypi_0    pypi
natsort                   8.4.0                    pypi_0    pypi
ncurses                   6.4                  h59595ed_2    conda-forge
networkx                  3.2.1                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numpy                     1.23.5                   pypi_0    pypi
numpy-groupies            0.10.2                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.18.1                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.3.101                 pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
openssl                   3.2.0                hd590300_1    conda-forge
packaging                 23.2                     pypi_0    pypi
pandas                    2.2.0                    pypi_0    pypi
patsy                     0.5.6                    pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
protobuf                  4.25.2                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
pyarrow                   15.0.0                   pypi_0    pypi
pyarrow-hotfix            0.6                      pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pynndescent               0.5.11                   pypi_0    pypi
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.1                    pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.13         hd12c33a_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pytz                      2023.3.post1             pypi_0    pypi
pyudorandom               1.0.0                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
ray                       2.9.1                    pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
referencing               0.32.1                   pypi_0    pypi
regex                     2023.12.25               pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
rpds-py                   0.17.1                   pypi_0    pypi
ruamel.yaml               0.17.21         py310h1fa729e_3    conda-forge
ruamel.yaml.clib          0.2.7           py310h2372a71_2    conda-forge
s2n                       1.4.0                h06160fa_0    conda-forge
s3fs                      2023.12.2                pypi_0    pypi
safetensors               0.4.2                    pypi_0    pypi
scanpy                    1.9.6                    pypi_0    pypi
scikit-learn              1.4.0                    pypi_0    pypi
scipy                     1.12.0                   pypi_0    pypi
seaborn                   0.13.1                   pypi_0    pypi
session-info              1.0.0                    pypi_0    pypi
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
somacore                  1.0.6                    pypi_0    pypi
statsmodels               0.14.1                   pypi_0    pypi
stdlib-list               0.10.0                   pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tdigest                   0.5.2.2                  pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tiledb                    0.24.0                   pypi_0    pypi
tiledbsoma                1.6.2                    pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tokenizers                0.15.1                   pypi_0    pypi
torch                     2.1.2                    pypi_0    pypi
torchdata                 0.7.1                    pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
transformers              4.37.0                   pypi_0    pypi
triton                    2.1.0                    pypi_0    pypi
typing-extensions         4.9.0                    pypi_0    pypi
tzdata                    2023.4                   pypi_0    pypi
umap-learn                0.5.5                    pypi_0    pypi
urllib3                   2.1.0                    pypi_0    pypi
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.16.0                   pypi_0    pypi
xxhash                    3.4.1                    pypi_0    pypi
xz                        5.2.6                h166bdaf_0    conda-forge
yarl                      1.9.4                    pypi_0    pypi
```

I can also send through the environment yml file but it's not allowed as an attachment on github

Thanks for your assistance, I'm excited to try geneformer with the CellxGene Census model.

**Comment by bkmartinjr** [comment]
I believe this was just fixed (not released) by PR #944 

CC: @atolopko-czi

**Comment by drneavin** [comment]
Hi @bkmartinjr, thanks for the fast reply. That's great news! I'll wait for the new release with this fix and see when it resolves it unless there's a dev version that I could test? Or an older version that would work?

**Comment by drneavin** [comment]
I can confirm that the updates in PR https://github.com/chanzuckerberg/cellxgene-census/pull/944 resolve this error by installing the update directly from github as suggested by @pablo-gar in PR [#951](https://github.com/chanzuckerberg/cellxgene-census/issues/951#issuecomment-1909205374). Thanks!

**Comment by bkmartinjr** [comment]
Thank you.  The fix will be in the next release (coming fairly soon)
